spring:
  application:
    name: springcloud-file-service
  rabbitmq:
    host: 192.168.6.36
    port: 5672
    username: guest
    password: 123456
    virtual-host: /
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8000

management:
  security:
    enabled: false

# Spring cloud eureka discovery
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Spring logging
logging:
  file: ${user.home}/spring-cloud-logs/${spring.application.name}-${server.port}.log

# Spring feign hystrix
feign:
  hystrix:
   enabled: true