spring:
  application:
    name: springcloud-eureka

server:
  port: 8761

management:
  security:
    enabled: false

eureka:
  instance:
    hostname: springcloud-eureka
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

logging:
  file: ${user.home}/spring-cloud-logs/${spring.application.name}-${server.port}.log

# Replica node 1
---
spring:
  application:
    name: springcloud-eureka
  profiles: replica1

server:
  port: 8761

eureka:
  instance:
    hostname: replica1
  client:
    service-url:
      defaultZone: http://replica2:8762/eureka/

# Replica node 2
---
spring:
  application:
    name: springcloud-eureka
  profiles: replica2

server:
  port: 8762

eureka:
  instance:
    hostname: replica2
  client:
    service-url:
      defaultZone: http://replica1:8761/eureka/
